
name: .NET Build

on:
  push:
    branches: [ "master", "main" ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: dotnet publish --configuration Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ClashXW-windows
        path: bin/Release/net8.0-windows/win-x64/publish/
